name: Run tests on the project
on:
  push:
    branches:
      - main
    paths:
      - 'typescript/**'
  pull_request:
    types:
      - opened
      - edited
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        
      - name: Link Checker
        uses: lycheeverse/lychee-action@c053181aa0c3d17606addfe97a9075a32723548a
        with:
          fail: true
          args: --scheme=https . --exclude-all-private
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run coverage